# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  name: LinuxAgentPool
  demands:
    - JDK -equals 11
    - Terraform -equals Yes
variables:
  isMaster: $[eq(variables['Build.sourceBranch'], 'refs/heads/master')]
stages:
  - stage: CheckingTheAgent
    condition: and(succeeded(), eq(variables.isMaster, true))
    pool:
      name: LinuxAgentPool
      demands:
        - Terraform -equals Yes
    variables:
      stage_version: "2.0.0"
      stage_email: "sraghu486@gmail.com"
    jobs:
      - job: CheckingTerraformPackerAndansibleTrivy
        variables:
          job_version: "3.0.0"
          job_email: "sraghu486@gmail.com"
        timeoutInMinutes: 5
        steps:
          - script: echo $(Build.BuildId)
            displayName: "Display The Build-ID"
          - script: terraform version && packer version && ansible --version && trivy --version
            displayName: "Display Terraform & Packer version"
          - script: docker version && docker ps && docker images && docker ps -a
            displayName: "Display Docker Version"
          - script: pwd && ls -al
            displayName: "Display List & Folders"
  - stage: SASTWithSonarQube
    condition: and(succeeded(), eq(variables.isDev, true))
    pool:
      name: LinuxAgentPool
      demands:
        - JDK -equals 11
    variables:
      SONAR_TOKEN: "0b7a2f7aba5c470f0e327dbb96104193a22213f2"
    jobs:
      - job: RunningSASTWithSonarqube
        timeoutInMinutes: 10
        steps:
          #SonarQube User Token need to be generated and used in the ServiceConnection.
          #Also change name of the project and artifactId(line 6 & 14) to ado-spring-boot-app-dev in POM.
          #No need to create a project in sonarqube as its created automatically.
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: "devopsb32_sonarqube-token"
              scannerMode: "Other"
              projectKey: "c6ecc3a736d2d4bf6d01437523cf442246e62bbc"
              projectName: "petclinic"
              projectVersion: "$(Build.BuildId)"
            displayName: "Preparing SonarQube Config"
          - task: Maven@4
            inputs:
              mavenPomFile: "pom.xml"
              publishJUnitResults: false
              javaHomeOption: "JDKVersion"
              mavenVersionOption: "Default"
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: "latest"
            displayName: "Running SonarQube Maven Analysis"
          - task: sonar-buildbreaker@8
            inputs:
              SonarQube: "devopsb32_sonarqube-token"
            displayName: "SAST Job Fail or Pass"
 - stage: BuildingJavaCodeWithMavenCopyToJFrog
   condition: always()
   pool:
    name: LinuxAgentPool
    demands:
     - Terraform -equals Yes
   jobs:
   - job: BuildingJavaCodeJob
     timeoutInMinutes: 5
     steps:
       - script: ls -al && pwd && rm -rf /home/ubuntu/.m2/settings.xml
         displayName: 'List Files & Current Working Directory'
       - task: DownloadSecureFile@1
         inputs:
           secureFile: 'settings.xml'
       - task: CopyFiles@2
         inputs:
           SourceFolder: '$(Agent.TempDirectory)'
           Contents: '**'
           TargetFolder: '/home/ubuntu/.m2'
       - script: mvn versions:set -DnewVersion=Dev-2.0.$(Build.BuildId)
         displayName: 'Set Maven Build Version'
       - script: mvn clean package install && ls -al
         displayName: 'Run the maven build and install'
       - script: mvn deploy && ls -al
         displayName: 'Run the maven deploy'
         continueOnError: true
       - script: ls -al && cp /home/ubuntu/myagent/_work/1/s/target/ado-spring-boot-app-dev-Dev-2.0.$(Build.BuildId).jar ROOT$(Build.BuildId).jar && ls -al
         displayName: 'List Files & Rename ROOT.jar'   
       - script: rm -rf /artifacts/*.jar && cp ROOT$(Build.BuildId).jar /artifacts && ls -al /artifacts
         displayName: 'Copy Artifact To Folder'
       - task: CopyFiles@2
         inputs:
           Contents: 'ROOT$(Build.BuildId).jar'
           TargetFolder: '$(Build.ArtifactStagingDirectory)'
           OverWrite: true
         displayName: 'Copying JAR file to ArtifactStagingDirector'
       - task: PublishBuildArtifacts@1
         inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'ROOT$(Build.BuildId).jar'
           publishLocation: 'Container'
         displayName: 'Publishing JAR Artifact.'
 